export const homeGallery = [
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/1-Modella Natale int.jpg",
    title: "Christmas Fashion Portrait",
    description: "Interior fashion portrait with festive styling",
    width: 600,
    height: 896,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Alina czechoslovak models 217 small.jpg",
    title: "Alina - Portrait 217",
    description: "Professional fashion portrait of Czechoslovak model Alina",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Alina czechoslovak models 364 small.jpg",
    title: "Alina - Portrait 364",
    description: "Elegant fashion portrait of model Alina",
    width: 2000,
    height: 3008,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Ana Grytsan -Miss Pantene 2010.jpg",
    title: "Ana Grytsan - Miss Pantene 2010",
    description: "Beauty portrait of Ana Grytsan, Miss Pantene 2010",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Ana and Krystyna olga agency 268 PURPLE OK !!! small.jpg",
    title: "Ana & Krystyna - Purple",
    description: "Olga Agency models Ana and Krystyna in purple styling",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0063 grafik small.jpg",
    title: "Graphic Fashion Portrait",
    description: "Artistic fashion portrait with graphic elements",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0302 small.jpg",
    title: "Fashion Editorial 302",
    description: "Contemporary fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0315 small.jpg",
    title: "Fashion Editorial 315",
    description: "Modern fashion portrait with dramatic lighting",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0349 small.jpg",
    title: "Fashion Editorial 349",
    description: "Professional fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0739 small.jpg",
    title: "Fashion Editorial 739",
    description: "Contemporary fashion portrait with artistic styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_0784 small.jpg",
    title: "Fashion Editorial 784",
    description: "Fashion photography with elegant composition",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_7935 small.jpg",
    title: "Fashion Editorial 7935",
    description: "Modern fashion portrait with professional styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_8350 small.jpg",
    title: "Fashion Editorial 8350",
    description: "Contemporary fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_8367 small.jpg",
    title: "Fashion Editorial 8367",
    description: "Professional fashion portrait with dramatic elements",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_8412 small.jpg",
    title: "Fashion Editorial 8412",
    description: "Artistic fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_8634 small.jpg",
    title: "Fashion Editorial 8634",
    description: "Modern fashion portrait with creative styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_8994 small.jpg",
    title: "Fashion Editorial 8994",
    description: "Contemporary fashion photography with bold composition",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9007 small.jpg",
    title: "Fashion Editorial 9007",
    description: "Professional fashion portrait with elegant lighting",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9238 small.jpg",
    title: "Fashion Editorial 9238",
    description: "Artistic fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9243 small.jpg",
    title: "Fashion Editorial 9243",
    description: "Modern fashion portrait with creative composition",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9248 small.jpg",
    title: "Fashion Editorial 9248",
    description: "Contemporary fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9261 small.jpg",
    title: "Fashion Editorial 9261",
    description: "Professional fashion portrait with dramatic styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9316 small.jpg",
    title: "Fashion Editorial 9316",
    description: "Artistic fashion photography with elegant elements",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9339 small.jpg",
    title: "Fashion Editorial 9339",
    description: "Modern fashion portrait with professional styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9347 small.jpg",
    title: "Fashion Editorial 9347",
    description: "Contemporary fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9360 small.jpg",
    title: "Fashion Editorial 9360",
    description: "Professional fashion portrait with creative lighting",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9383 small.jpg",
    title: "Fashion Editorial 9383",
    description: "Artistic fashion photography with bold composition",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9384 small.jpg",
    title: "Fashion Editorial 9384",
    description: "Modern fashion portrait with elegant styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/CER_9394 BICOLOR small.jpg",
    title: "Fashion Editorial - Bicolor",
    description: "Contemporary fashion photography with bicolor treatment",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina K Czechoslovak models 107 big small Ok.jpg",
    title: "Christina K - Portrait 107",
    description: "Czechoslovak model Christina K professional portrait",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina K Czechoslovak models 221 small.jpg",
    title: "Christina K - Portrait 221",
    description: "Professional fashion portrait of Christina K",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina Karteri 1.jpg",
    title: "Christina Karteri - Portrait 1",
    description: "Fashion photography portrait of model Christina Karteri",
    width: 600,
    height: 894,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina Karteri 2.jpg",
    title: "Christina Karteri - Portrait 2",
    description: "Contemporary portrait of Christina Karteri",
    width: 600,
    height: 894,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina Karteri 3.jpg",
    title: "Christina Karteri - Portrait 3",
    description: "Professional fashion portrait of Christina Karteri",
    width: 600,
    height: 894,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Christina Karteri-ritratto 399-BIG.jpg",
    title: "Christina Karteri - Close Portrait",
    description: "Intimate portrait of Christina Karteri with dramatic lighting",
    width: 1944,
    height: 2896,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/DSC_0427 small.jpg",
    title: "Fashion Portrait 427",
    description: "Contemporary fashion photography portrait",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/DSC_8785 small.jpg",
    title: "Fashion Portrait 8785",
    description: "Professional fashion portrait with creative styling",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/DSC_8865 small.jpg",
    title: "Fashion Portrait 8865",
    description: "Modern fashion photography with elegant composition",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/DSC_8938 small.jpg",
    title: "Fashion Portrait 8938",
    description: "Artistic fashion portrait with professional lighting",
    width: 2848,
    height: 4288,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Elisa 1 int.jpg",
    title: "Elisa - Interior Portrait",
    description: "Interior fashion portrait of model Elisa",
    width: 600,
    height: 896,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Euzenya 1 ext.jpg",
    title: "Euzenya - Outdoor Portrait 1",
    description: "Exterior fashion portrait of model Euzenya",
    width: 2000,
    height: 3008,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Euzenya 2 ext.jpg",
    title: "Euzenya - Outdoor Portrait 2",
    description: "Outdoor fashion photography of Euzenya in natural light",
    width: 2000,
    height: 3008,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Eva Katzerova 195 BLUE OK small.jpg",
    title: "Eva Katzerova - Blue",
    description: "Model Eva Katzerova in blue styling with professional lighting",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Helena K. czechoslovakmodels 025 bright purple small.jpg",
    title: "Helena K - Bright Purple",
    description: "Czechoslovak model Helena K in vibrant purple tones",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Helena K. czechoslovakmodels 063 purple small.jpg",
    title: "Helena K - Purple Portrait",
    description: "Fashion portrait of Helena K with purple styling",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Katya Bauerova 162 ok small.jpg",
    title: "Katya Bauerova - Portrait 162",
    description: "Professional fashion portrait of model Katya Bauerova",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Katya Bauerova 351 ok small.jpg",
    title: "Katya Bauerova - Portrait 351",
    description: "Contemporary fashion photography of Katya Bauerova",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Kristina Zarubina -Claudia Cardinale OK ! small.jpg",
    title: "Kristina Zarubina - Classic Style",
    description: "Kristina Zarubina in classic Claudia Cardinale inspired styling",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Krystina Kucirkova 009 OK soft small.jpg",
    title: "Krystina Kucirkova - Soft Portrait",
    description: "Model Krystina Kucirkova in soft, elegant styling",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Lukas Zrust-1 ok.jpg",
    title: "Lukas Zrust",
    description: "Male fashion portrait of model Lukas Zrust",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Magdalena glamour 1.jpg",
    title: "Magdalena - Glamour",
    description: "Glamour portrait of model Magdalena with elegant styling",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Michaela Nedomova 052 OK small.jpg",
    title: "Michaela Nedomova - Portrait 052",
    description: "Professional fashion portrait of Michaela Nedomova",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Michaela Nedomova 064 OK SMALL.jpg",
    title: "Michaela Nedomova - Portrait 064",
    description: "Contemporary fashion photography of Michaela Nedomova",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Modella Bocca grande 1.jpg",
    title: "Expressive Beauty",
    description: "Dramatic fashion portrait highlighting expressive features",
    width: 600,
    height: 896,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Muz 1.jpg",
    title: "Male Fashion Portrait",
    description: "Contemporary male fashion photography",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Ponte Carlo ext 1.jpg",
    title: "Charles Bridge Fashion",
    description: "Outdoor fashion photography at Ponte Carlo",
    width: 600,
    height: 896,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Radek Dongres-Czechoslovak Models 332 small.jpg",
    title: "Radek Dongres",
    description: "Czechoslovak Models male fashion portrait of Radek Dongres",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Ritratto bella ragazza con mano.jpg",
    title: "Elegant Hand Portrait",
    description: "Beautiful portrait with elegant hand composition",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Sarka Hulinkova-Czechoslovak models 332 small.jpg",
    title: "Sarka Hulinkova - Portrait 332",
    description: "Czechoslovak model Sarka Hulinkova fashion portrait",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Sarka Hulinkova-FOTO 1 small.jpg",
    title: "Sarka Hulinkova - Portrait 1",
    description: "Professional fashion portrait of Sarka Hulinkova",
    width: 600,
    height: 902,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/Viktoria 1 BW.jpg",
    title: "Viktoria - Black & White",
    description: "Artistic black and white portrait of model Viktoria",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/_USA0691 small.jpg",
    title: "USA Fashion - Portrait 691",
    description: "Fashion photography from USA collection",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/_USA0864 small.jpg",
    title: "USA Fashion - Portrait 864",
    description: "Contemporary fashion portrait from USA series",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/_USA1620 small.jpg",
    title: "USA Fashion - Portrait 1620",
    description: "Professional fashion photography from USA collection",
    width: 2592,
    height: 3872,
  },
  {
    src: "http://emanueldellapia.com/E_fotky/fashion/_USA1707 small.jpg",
    title: "USA Fashion - Portrait 1707",
    description: "Modern fashion portrait from USA series",
    width: 2592,
    height: 3872,
  },
];
