export const routes = {
  home: "/",
  about: "/about",
  calendars: "/calendars",
  contact: "/contact",
  fashion: "/fashion",
  portraits: "/portraits",
  fineArt: "/fine-art",
  services: "/services",
  travel: "/travel",
  weddings: "/weddings",
  workshops: "/workshops",
  glamour: "/glamour",
  videoclips: "/videoclips",
} as const;
